version: '3'
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATAVASE: utopia
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: D8abaseCred@ials
    ports:
      - '3306:3306'

  utopia_spring:
    build:
      context: ./utopia_spring
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - './utopia_spring:/app'
    links:
      - "mysql:mysql"

  user:
    build:
      context: ./user
    expose:
      - "8081"
    ports:
      - "8081:8080"
    volumes:
      - './user:/app'
    links:
      - "mysql:mysql"
